language: go
go:
- 1.7.1
before_install:
- sudo apt-get install libXxf86vm-dev
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
before_script:
- go vet ./...
script:
- go test -v -covermode=count -coverprofile=coverage.out ./core/
- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: MOYMXA0Tkj8RHrvsfh+0/oL4KW3p/W08Xe0787H2eF7PbpweejHB8SJoJCS8NpIkHzd88Ow6iB7ewB+uvJMchFLUaj0hh2Cbia2TmUX8tFnWtQ6umr+4AHqUA4OB1K1F1WLnOQ6RXoIL/oxkffldXjFdhd3+OthYznrUfVorbugj00zUIz83c7lQDZ0jOvQq+Qq671Jg/1zdeyhDf9cgTBlGWehtpngFT2VEghn47N+kL+pYJRdi+DLaYicovaQNoEvwJaP88Zm4D5fa8GMa/rNvtWs0rgXsJ53IrCJkXNYJSCnMq0TipT+/50KbdSDnLL3sUcAYjDqx+JC4MWW9Yi7MfqoktONWHe/x74sFXup61KEX848Pl+GY/y27E9tKWy9XHLk7M9bZfx0SArTZeApzJ3i8KRSV/Mm3IMC06azGSPiGtZj5fLbYHduLXw+scEwW2KByxI0mErgOhT2xSvt3vrY2U+FmFm6hdSMtgnxFXIenOMwuhUzpOcHVuYgfoXaH0+YAw6u8fM5OvMm+WMfe66GZGecThAIvmNrPbl0WDcN8/tNSdKmWs36Fhl67Q6YN1I0Q+g2OX83XPlUT6u6ruZBj3Ulw7AIobAtczn56ikluny/8wZFcTjW033EoFg51xyehEcaFXjGEqapxmPaR4zCZMiD4Zh0gROo00Ec=
